image: ubuntu

configuration: Release

nuget:
  account_feed: true
  project_feed: true
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

install:
- sh: ls
- cmd: dir

services:
- mysql
- redis

before_build:
- echo "Before build!"
- cmd: nuget restore
- sh: dotnet restore -v normal

build:
  project: UbuntuDotNetCoreTests.sln
  parallel: true
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
