image: ubuntu

configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

install:
- sh: ls
- cmd: dir

before_build:
- echo "Before build!"
- cmd: nuget restore

build:
  project: UbuntuDotNetCoreTests.sln
  parallel: true
  verbosity: normal
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
